on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    # This checks if the PR author has a trusted association
    if: >-
      ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && 
      contains(fromJson('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.pull_request.author_association) }}
    # if: ${{ github.event.pull_request.author_association == 'COLLABORATOR' || github.event.pull_request.author_association == 'MEMBER' || github.event.pull_request.author_association == 'OWNER' }}
    
    steps:
      - uses: actions/checkout@v3
      - name: Run Maintainer Script
        run: |
          echo "This script only runs for maintainers."
          echo "User: ${{ github.actor }}"
          echo "${{ github.event.pull_request.author }}"
          echo "Association: ${{ github.event.pull_request.author_association }}"

